### ISSUE TITLE
Error: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by eja-git** [gefyrahq/gefyra-docker-desktop-extension#44] opened 2023-03-01 16:11 UTC
Trying to follow along with the youtube demo: https://www.youtube.com/watch?v=4xmaOVul5Ww

These are my settings, using built-in Docker Desktop K8S.  I'm on the latest version of Gefyra extension for Docker Desktop. 

![image](https://user-images.githubusercontent.com/3740288/222196107-714a72f0-5451-42c6-89a0-9a4939f81d60.png)

![image](https://user-images.githubusercontent.com/3740288/222196270-89e94880-cf1c-4fe6-8a14-31c152c80b55.png)

And the result:

![image](https://user-images.githubusercontent.com/3740288/222196819-780dcaf5-ae03-4566-8ee6-e014b9945e4b.png)

**Comment by Schille** [comment] 2023-03-02 18:16
Thanks @eja-git for reporting this issue. 
What system are you running on? Seems like Windows, but which version exactly?
Did you install it from the Docker Desktop extension marketplace?

**Comment by eja-git** [comment] 2023-03-02 19:35
Here are the exact specs of my system: 

![image](https://user-images.githubusercontent.com/3740288/222532780-30a30e47-1e44-4173-80c8-88f53075a638.png)

Yes, I have Docker Desktop (v4.16.3) set to use WSL2 backend. (and to enable Kubernetes v1.25.4)

I did install Gefyra Extension via the Docker Desktop Extensions Marketplace.

**Comment by Schille** [comment] 2023-03-14 09:22
Hi @eja-git 
Thanks again for reporting this. I was able to reproduce the error running my own Windows 10 Pro (with Ubuntu 22.02 LTS on WSL 2). I pinned the error down to the volume mounts, because if I don't set them, the operation succeeds. 
Now I am off to resolve the issue.

**Comment by SteinRobert** [comment] 2023-03-14 22:24
@eja-git we just released a new version - 1.1.3. This bug should be fixed there - could you check please? Thank you again for reporting and helping us improve Gefyra :)

**Closed** 2023-03-15 15:18 UTC
